spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: changemeinprod!
app.cors.allowed-origins=http://localhost:8000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=your_redis_password 